I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name u'start' is defined twice, at game/script.rpy:38 and game/tutorial_chain.rpy:10.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-6.99.8-sdk\renpy\bootstrap.py", line 281, in bootstrap
    renpy.main.main()
  File "D:\renpy-6.99.8-sdk\renpy\main.py", line 351, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "D:\renpy-6.99.8-sdk\renpy\script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "D:\renpy-6.99.8-sdk\renpy\script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "D:\renpy-6.99.8-sdk\renpy\script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'start' is defined twice, at game/script.rpy:38 and game/tutorial_chain.rpy:10.

Windows-8-6.2.9200
Ren'Py 6.99.8.959
 
